set(_CATKIN_CURRENT_PACKAGE "modbus_arm")
set(modbus_arm_VERSION "0.0.0")
set(modbus_arm_MAINTAINER "allen <allen@todo.todo>")
set(modbus_arm_PACKAGE_FORMAT "2")
set(modbus_arm_BUILD_DEPENDS "roscpp" "std_msgs")
set(modbus_arm_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(modbus_arm_BUILDTOOL_DEPENDS "catkin")
set(modbus_arm_BUILDTOOL_EXPORT_DEPENDS )
set(modbus_arm_EXEC_DEPENDS "roscpp" "std_msgs")
set(modbus_arm_RUN_DEPENDS "roscpp" "std_msgs")
set(modbus_arm_TEST_DEPENDS )
set(modbus_arm_DOC_DEPENDS )
set(modbus_arm_URL_WEBSITE "")
set(modbus_arm_URL_BUGTRACKER "")
set(modbus_arm_URL_REPOSITORY "")
set(modbus_arm_DEPRECATED "")