set(_CATKIN_CURRENT_PACKAGE "interface")
set(interface_VERSION "0.0.0")
set(interface_MAINTAINER "allen <allen@todo.todo>")
set(interface_PACKAGE_FORMAT "2")
set(interface_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "vision_pro" "cv_bridge" "image_transport" "message_runtime" "sensor_msgs" "message_generation")
set(interface_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "cv_bridge" "image_transport" "message_runtime" "sensor_msgs" "message_generation")
set(interface_BUILDTOOL_DEPENDS "catkin")
set(interface_BUILDTOOL_EXPORT_DEPENDS )
set(interface_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "cv_bridge" "image_transport" "message_runtime" "sensor_msgs")
set(interface_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "cv_bridge" "image_transport" "message_runtime" "sensor_msgs" "message_generation")
set(interface_TEST_DEPENDS )
set(interface_DOC_DEPENDS )
set(interface_URL_WEBSITE "")
set(interface_URL_BUGTRACKER "")
set(interface_URL_REPOSITORY "")
set(interface_DEPRECATED "")